// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ArticlesColumns holds the columns for the "articles" table.
	ArticlesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "video_url", Type: field.TypeString},
		{Name: "video_id", Type: field.TypeString},
		{Name: "uploader", Type: field.TypeString},
		{Name: "uploader_url", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "title", Type: field.TypeString},
		{Name: "thumbnail", Type: field.TypeString},
		{Name: "html", Type: field.TypeString},
		{Name: "user_options_article", Type: field.TypeInt, Unique: true, Nullable: true},
	}
	// ArticlesTable holds the schema information for the "articles" table.
	ArticlesTable = &schema.Table{
		Name:       "articles",
		Columns:    ArticlesColumns,
		PrimaryKey: []*schema.Column{ArticlesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "articles_user_options_article",
				Columns:    []*schema.Column{ArticlesColumns[9]},
				RefColumns: []*schema.Column{UserOptionsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// PhaseOptionsColumns holds the columns for the "phase_options" table.
	PhaseOptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "phase_name", Type: field.TypeString},
		{Name: "client", Type: field.TypeString, Nullable: true},
		{Name: "model", Type: field.TypeString, Nullable: true},
		{Name: "prompt", Type: field.TypeString, Nullable: true},
		{Name: "user_options_phase_options", Type: field.TypeInt, Nullable: true},
	}
	// PhaseOptionsTable holds the schema information for the "phase_options" table.
	PhaseOptionsTable = &schema.Table{
		Name:       "phase_options",
		Columns:    PhaseOptionsColumns,
		PrimaryKey: []*schema.Column{PhaseOptionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "phase_options_user_options_phase_options",
				Columns:    []*schema.Column{PhaseOptionsColumns[5]},
				RefColumns: []*schema.Column{UserOptionsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UserOptionsColumns holds the columns for the "user_options" table.
	UserOptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "video_url", Type: field.TypeString},
		{Name: "user_style_prompt", Type: field.TypeString, Nullable: true},
		{Name: "client", Type: field.TypeString, Nullable: true},
		{Name: "model", Type: field.TypeString, Nullable: true},
		{Name: "mode", Type: field.TypeString, Nullable: true},
		{Name: "chapters_as_sections", Type: field.TypeBool, Default: false},
		{Name: "embed_video", Type: field.TypeBool, Default: false},
		{Name: "include_description", Type: field.TypeBool, Default: false},
		{Name: "include_tags", Type: field.TypeBool, Default: false},
	}
	// UserOptionsTable holds the schema information for the "user_options" table.
	UserOptionsTable = &schema.Table{
		Name:       "user_options",
		Columns:    UserOptionsColumns,
		PrimaryKey: []*schema.Column{UserOptionsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ArticlesTable,
		PhaseOptionsTable,
		UserOptionsTable,
	}
)

func init() {
	ArticlesTable.ForeignKeys[0].RefTable = UserOptionsTable
	PhaseOptionsTable.ForeignKeys[0].RefTable = UserOptionsTable
}
