// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Article is the predicate function for article builders.
type Article func(*sql.Selector)

// PhaseOptions is the predicate function for phaseoptions builders.
type PhaseOptions func(*sql.Selector)

// UserOptions is the predicate function for useroptions builders.
type UserOptions func(*sql.Selector)
