// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"gitlab.aaronhess.xyz/viddler/viddler-blog-api/internal/db/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"gitlab.aaronhess.xyz/viddler/viddler-blog-api/internal/db/ent/article"
	"gitlab.aaronhess.xyz/viddler/viddler-blog-api/internal/db/ent/phaseoptions"
	"gitlab.aaronhess.xyz/viddler/viddler-blog-api/internal/db/ent/useroptions"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Article is the client for interacting with the Article builders.
	Article *ArticleClient
	// PhaseOptions is the client for interacting with the PhaseOptions builders.
	PhaseOptions *PhaseOptionsClient
	// UserOptions is the client for interacting with the UserOptions builders.
	UserOptions *UserOptionsClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Article = NewArticleClient(c.config)
	c.PhaseOptions = NewPhaseOptionsClient(c.config)
	c.UserOptions = NewUserOptionsClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:          ctx,
		config:       cfg,
		Article:      NewArticleClient(cfg),
		PhaseOptions: NewPhaseOptionsClient(cfg),
		UserOptions:  NewUserOptionsClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:          ctx,
		config:       cfg,
		Article:      NewArticleClient(cfg),
		PhaseOptions: NewPhaseOptionsClient(cfg),
		UserOptions:  NewUserOptionsClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Article.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Article.Use(hooks...)
	c.PhaseOptions.Use(hooks...)
	c.UserOptions.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Article.Intercept(interceptors...)
	c.PhaseOptions.Intercept(interceptors...)
	c.UserOptions.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ArticleMutation:
		return c.Article.mutate(ctx, m)
	case *PhaseOptionsMutation:
		return c.PhaseOptions.mutate(ctx, m)
	case *UserOptionsMutation:
		return c.UserOptions.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ArticleClient is a client for the Article schema.
type ArticleClient struct {
	config
}

// NewArticleClient returns a client for the Article from the given config.
func NewArticleClient(c config) *ArticleClient {
	return &ArticleClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `article.Hooks(f(g(h())))`.
func (c *ArticleClient) Use(hooks ...Hook) {
	c.hooks.Article = append(c.hooks.Article, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `article.Intercept(f(g(h())))`.
func (c *ArticleClient) Intercept(interceptors ...Interceptor) {
	c.inters.Article = append(c.inters.Article, interceptors...)
}

// Create returns a builder for creating a Article entity.
func (c *ArticleClient) Create() *ArticleCreate {
	mutation := newArticleMutation(c.config, OpCreate)
	return &ArticleCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Article entities.
func (c *ArticleClient) CreateBulk(builders ...*ArticleCreate) *ArticleCreateBulk {
	return &ArticleCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ArticleClient) MapCreateBulk(slice any, setFunc func(*ArticleCreate, int)) *ArticleCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ArticleCreateBulk{err: fmt.Errorf("calling to ArticleClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ArticleCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ArticleCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Article.
func (c *ArticleClient) Update() *ArticleUpdate {
	mutation := newArticleMutation(c.config, OpUpdate)
	return &ArticleUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ArticleClient) UpdateOne(a *Article) *ArticleUpdateOne {
	mutation := newArticleMutation(c.config, OpUpdateOne, withArticle(a))
	return &ArticleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ArticleClient) UpdateOneID(id int) *ArticleUpdateOne {
	mutation := newArticleMutation(c.config, OpUpdateOne, withArticleID(id))
	return &ArticleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Article.
func (c *ArticleClient) Delete() *ArticleDelete {
	mutation := newArticleMutation(c.config, OpDelete)
	return &ArticleDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ArticleClient) DeleteOne(a *Article) *ArticleDeleteOne {
	return c.DeleteOneID(a.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ArticleClient) DeleteOneID(id int) *ArticleDeleteOne {
	builder := c.Delete().Where(article.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ArticleDeleteOne{builder}
}

// Query returns a query builder for Article.
func (c *ArticleClient) Query() *ArticleQuery {
	return &ArticleQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeArticle},
		inters: c.Interceptors(),
	}
}

// Get returns a Article entity by its id.
func (c *ArticleClient) Get(ctx context.Context, id int) (*Article, error) {
	return c.Query().Where(article.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ArticleClient) GetX(ctx context.Context, id int) *Article {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUserOptions queries the user_options edge of a Article.
func (c *ArticleClient) QueryUserOptions(a *Article) *UserOptionsQuery {
	query := (&UserOptionsClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := a.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(article.Table, article.FieldID, id),
			sqlgraph.To(useroptions.Table, useroptions.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, article.UserOptionsTable, article.UserOptionsColumn),
		)
		fromV = sqlgraph.Neighbors(a.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ArticleClient) Hooks() []Hook {
	return c.hooks.Article
}

// Interceptors returns the client interceptors.
func (c *ArticleClient) Interceptors() []Interceptor {
	return c.inters.Article
}

func (c *ArticleClient) mutate(ctx context.Context, m *ArticleMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ArticleCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ArticleUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ArticleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ArticleDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Article mutation op: %q", m.Op())
	}
}

// PhaseOptionsClient is a client for the PhaseOptions schema.
type PhaseOptionsClient struct {
	config
}

// NewPhaseOptionsClient returns a client for the PhaseOptions from the given config.
func NewPhaseOptionsClient(c config) *PhaseOptionsClient {
	return &PhaseOptionsClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `phaseoptions.Hooks(f(g(h())))`.
func (c *PhaseOptionsClient) Use(hooks ...Hook) {
	c.hooks.PhaseOptions = append(c.hooks.PhaseOptions, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `phaseoptions.Intercept(f(g(h())))`.
func (c *PhaseOptionsClient) Intercept(interceptors ...Interceptor) {
	c.inters.PhaseOptions = append(c.inters.PhaseOptions, interceptors...)
}

// Create returns a builder for creating a PhaseOptions entity.
func (c *PhaseOptionsClient) Create() *PhaseOptionsCreate {
	mutation := newPhaseOptionsMutation(c.config, OpCreate)
	return &PhaseOptionsCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PhaseOptions entities.
func (c *PhaseOptionsClient) CreateBulk(builders ...*PhaseOptionsCreate) *PhaseOptionsCreateBulk {
	return &PhaseOptionsCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PhaseOptionsClient) MapCreateBulk(slice any, setFunc func(*PhaseOptionsCreate, int)) *PhaseOptionsCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PhaseOptionsCreateBulk{err: fmt.Errorf("calling to PhaseOptionsClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PhaseOptionsCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PhaseOptionsCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PhaseOptions.
func (c *PhaseOptionsClient) Update() *PhaseOptionsUpdate {
	mutation := newPhaseOptionsMutation(c.config, OpUpdate)
	return &PhaseOptionsUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PhaseOptionsClient) UpdateOne(po *PhaseOptions) *PhaseOptionsUpdateOne {
	mutation := newPhaseOptionsMutation(c.config, OpUpdateOne, withPhaseOptions(po))
	return &PhaseOptionsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PhaseOptionsClient) UpdateOneID(id int) *PhaseOptionsUpdateOne {
	mutation := newPhaseOptionsMutation(c.config, OpUpdateOne, withPhaseOptionsID(id))
	return &PhaseOptionsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PhaseOptions.
func (c *PhaseOptionsClient) Delete() *PhaseOptionsDelete {
	mutation := newPhaseOptionsMutation(c.config, OpDelete)
	return &PhaseOptionsDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PhaseOptionsClient) DeleteOne(po *PhaseOptions) *PhaseOptionsDeleteOne {
	return c.DeleteOneID(po.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PhaseOptionsClient) DeleteOneID(id int) *PhaseOptionsDeleteOne {
	builder := c.Delete().Where(phaseoptions.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PhaseOptionsDeleteOne{builder}
}

// Query returns a query builder for PhaseOptions.
func (c *PhaseOptionsClient) Query() *PhaseOptionsQuery {
	return &PhaseOptionsQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePhaseOptions},
		inters: c.Interceptors(),
	}
}

// Get returns a PhaseOptions entity by its id.
func (c *PhaseOptionsClient) Get(ctx context.Context, id int) (*PhaseOptions, error) {
	return c.Query().Where(phaseoptions.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PhaseOptionsClient) GetX(ctx context.Context, id int) *PhaseOptions {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUserOptions queries the user_options edge of a PhaseOptions.
func (c *PhaseOptionsClient) QueryUserOptions(po *PhaseOptions) *UserOptionsQuery {
	query := (&UserOptionsClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := po.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(phaseoptions.Table, phaseoptions.FieldID, id),
			sqlgraph.To(useroptions.Table, useroptions.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, phaseoptions.UserOptionsTable, phaseoptions.UserOptionsColumn),
		)
		fromV = sqlgraph.Neighbors(po.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PhaseOptionsClient) Hooks() []Hook {
	return c.hooks.PhaseOptions
}

// Interceptors returns the client interceptors.
func (c *PhaseOptionsClient) Interceptors() []Interceptor {
	return c.inters.PhaseOptions
}

func (c *PhaseOptionsClient) mutate(ctx context.Context, m *PhaseOptionsMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PhaseOptionsCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PhaseOptionsUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PhaseOptionsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PhaseOptionsDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PhaseOptions mutation op: %q", m.Op())
	}
}

// UserOptionsClient is a client for the UserOptions schema.
type UserOptionsClient struct {
	config
}

// NewUserOptionsClient returns a client for the UserOptions from the given config.
func NewUserOptionsClient(c config) *UserOptionsClient {
	return &UserOptionsClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `useroptions.Hooks(f(g(h())))`.
func (c *UserOptionsClient) Use(hooks ...Hook) {
	c.hooks.UserOptions = append(c.hooks.UserOptions, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `useroptions.Intercept(f(g(h())))`.
func (c *UserOptionsClient) Intercept(interceptors ...Interceptor) {
	c.inters.UserOptions = append(c.inters.UserOptions, interceptors...)
}

// Create returns a builder for creating a UserOptions entity.
func (c *UserOptionsClient) Create() *UserOptionsCreate {
	mutation := newUserOptionsMutation(c.config, OpCreate)
	return &UserOptionsCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of UserOptions entities.
func (c *UserOptionsClient) CreateBulk(builders ...*UserOptionsCreate) *UserOptionsCreateBulk {
	return &UserOptionsCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserOptionsClient) MapCreateBulk(slice any, setFunc func(*UserOptionsCreate, int)) *UserOptionsCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserOptionsCreateBulk{err: fmt.Errorf("calling to UserOptionsClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserOptionsCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserOptionsCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for UserOptions.
func (c *UserOptionsClient) Update() *UserOptionsUpdate {
	mutation := newUserOptionsMutation(c.config, OpUpdate)
	return &UserOptionsUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserOptionsClient) UpdateOne(uo *UserOptions) *UserOptionsUpdateOne {
	mutation := newUserOptionsMutation(c.config, OpUpdateOne, withUserOptions(uo))
	return &UserOptionsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserOptionsClient) UpdateOneID(id int) *UserOptionsUpdateOne {
	mutation := newUserOptionsMutation(c.config, OpUpdateOne, withUserOptionsID(id))
	return &UserOptionsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for UserOptions.
func (c *UserOptionsClient) Delete() *UserOptionsDelete {
	mutation := newUserOptionsMutation(c.config, OpDelete)
	return &UserOptionsDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserOptionsClient) DeleteOne(uo *UserOptions) *UserOptionsDeleteOne {
	return c.DeleteOneID(uo.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserOptionsClient) DeleteOneID(id int) *UserOptionsDeleteOne {
	builder := c.Delete().Where(useroptions.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserOptionsDeleteOne{builder}
}

// Query returns a query builder for UserOptions.
func (c *UserOptionsClient) Query() *UserOptionsQuery {
	return &UserOptionsQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUserOptions},
		inters: c.Interceptors(),
	}
}

// Get returns a UserOptions entity by its id.
func (c *UserOptionsClient) Get(ctx context.Context, id int) (*UserOptions, error) {
	return c.Query().Where(useroptions.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserOptionsClient) GetX(ctx context.Context, id int) *UserOptions {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryArticle queries the article edge of a UserOptions.
func (c *UserOptionsClient) QueryArticle(uo *UserOptions) *ArticleQuery {
	query := (&ArticleClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := uo.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(useroptions.Table, useroptions.FieldID, id),
			sqlgraph.To(article.Table, article.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, useroptions.ArticleTable, useroptions.ArticleColumn),
		)
		fromV = sqlgraph.Neighbors(uo.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryPhaseOptions queries the phase_options edge of a UserOptions.
func (c *UserOptionsClient) QueryPhaseOptions(uo *UserOptions) *PhaseOptionsQuery {
	query := (&PhaseOptionsClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := uo.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(useroptions.Table, useroptions.FieldID, id),
			sqlgraph.To(phaseoptions.Table, phaseoptions.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, useroptions.PhaseOptionsTable, useroptions.PhaseOptionsColumn),
		)
		fromV = sqlgraph.Neighbors(uo.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserOptionsClient) Hooks() []Hook {
	return c.hooks.UserOptions
}

// Interceptors returns the client interceptors.
func (c *UserOptionsClient) Interceptors() []Interceptor {
	return c.inters.UserOptions
}

func (c *UserOptionsClient) mutate(ctx context.Context, m *UserOptionsMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserOptionsCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserOptionsUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserOptionsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserOptionsDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown UserOptions mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Article, PhaseOptions, UserOptions []ent.Hook
	}
	inters struct {
		Article, PhaseOptions, UserOptions []ent.Interceptor
	}
)
