// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.aaronhess.xyz/viddler/viddler-blog-api/internal/db/ent/phaseoptions"
	"gitlab.aaronhess.xyz/viddler/viddler-blog-api/internal/db/ent/predicate"
)

// PhaseOptionsDelete is the builder for deleting a PhaseOptions entity.
type PhaseOptionsDelete struct {
	config
	hooks    []Hook
	mutation *PhaseOptionsMutation
}

// Where appends a list predicates to the PhaseOptionsDelete builder.
func (pod *PhaseOptionsDelete) Where(ps ...predicate.PhaseOptions) *PhaseOptionsDelete {
	pod.mutation.Where(ps...)
	return pod
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pod *PhaseOptionsDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, pod.sqlExec, pod.mutation, pod.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (pod *PhaseOptionsDelete) ExecX(ctx context.Context) int {
	n, err := pod.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pod *PhaseOptionsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(phaseoptions.Table, sqlgraph.NewFieldSpec(phaseoptions.FieldID, field.TypeInt))
	if ps := pod.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pod.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	pod.mutation.done = true
	return affected, err
}

// PhaseOptionsDeleteOne is the builder for deleting a single PhaseOptions entity.
type PhaseOptionsDeleteOne struct {
	pod *PhaseOptionsDelete
}

// Where appends a list predicates to the PhaseOptionsDelete builder.
func (podo *PhaseOptionsDeleteOne) Where(ps ...predicate.PhaseOptions) *PhaseOptionsDeleteOne {
	podo.pod.mutation.Where(ps...)
	return podo
}

// Exec executes the deletion query.
func (podo *PhaseOptionsDeleteOne) Exec(ctx context.Context) error {
	n, err := podo.pod.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{phaseoptions.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (podo *PhaseOptionsDeleteOne) ExecX(ctx context.Context) {
	if err := podo.Exec(ctx); err != nil {
		panic(err)
	}
}
