// Code generated by ent, DO NOT EDIT.

package ent

import (
	"gitlab.aaronhess.xyz/viddler/viddler-blog-api/internal/db/ent/article"
	"gitlab.aaronhess.xyz/viddler/viddler-blog-api/internal/db/ent/phaseoptions"
	"gitlab.aaronhess.xyz/viddler/viddler-blog-api/internal/db/ent/schema"
	"gitlab.aaronhess.xyz/viddler/viddler-blog-api/internal/db/ent/useroptions"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	articleFields := schema.Article{}.Fields()
	_ = articleFields
	// articleDescVideoURL is the schema descriptor for video_url field.
	articleDescVideoURL := articleFields[0].Descriptor()
	// article.VideoURLValidator is a validator for the "video_url" field. It is called by the builders before save.
	article.VideoURLValidator = articleDescVideoURL.Validators[0].(func(string) error)
	// articleDescVideoID is the schema descriptor for video_id field.
	articleDescVideoID := articleFields[1].Descriptor()
	// article.VideoIDValidator is a validator for the "video_id" field. It is called by the builders before save.
	article.VideoIDValidator = articleDescVideoID.Validators[0].(func(string) error)
	// articleDescUploader is the schema descriptor for uploader field.
	articleDescUploader := articleFields[2].Descriptor()
	// article.UploaderValidator is a validator for the "uploader" field. It is called by the builders before save.
	article.UploaderValidator = articleDescUploader.Validators[0].(func(string) error)
	// articleDescUploaderURL is the schema descriptor for uploader_url field.
	articleDescUploaderURL := articleFields[3].Descriptor()
	// article.UploaderURLValidator is a validator for the "uploader_url" field. It is called by the builders before save.
	article.UploaderURLValidator = articleDescUploaderURL.Validators[0].(func(string) error)
	// articleDescDescription is the schema descriptor for description field.
	articleDescDescription := articleFields[4].Descriptor()
	// article.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	article.DescriptionValidator = articleDescDescription.Validators[0].(func(string) error)
	// articleDescTitle is the schema descriptor for title field.
	articleDescTitle := articleFields[5].Descriptor()
	// article.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	article.TitleValidator = articleDescTitle.Validators[0].(func(string) error)
	// articleDescThumbnail is the schema descriptor for thumbnail field.
	articleDescThumbnail := articleFields[6].Descriptor()
	// article.ThumbnailValidator is a validator for the "thumbnail" field. It is called by the builders before save.
	article.ThumbnailValidator = articleDescThumbnail.Validators[0].(func(string) error)
	phaseoptionsFields := schema.PhaseOptions{}.Fields()
	_ = phaseoptionsFields
	// phaseoptionsDescPhaseName is the schema descriptor for phase_name field.
	phaseoptionsDescPhaseName := phaseoptionsFields[0].Descriptor()
	// phaseoptions.PhaseNameValidator is a validator for the "phase_name" field. It is called by the builders before save.
	phaseoptions.PhaseNameValidator = phaseoptionsDescPhaseName.Validators[0].(func(string) error)
	useroptionsFields := schema.UserOptions{}.Fields()
	_ = useroptionsFields
	// useroptionsDescVideoURL is the schema descriptor for video_url field.
	useroptionsDescVideoURL := useroptionsFields[0].Descriptor()
	// useroptions.VideoURLValidator is a validator for the "video_url" field. It is called by the builders before save.
	useroptions.VideoURLValidator = useroptionsDescVideoURL.Validators[0].(func(string) error)
	// useroptionsDescChaptersAsSections is the schema descriptor for chapters_as_sections field.
	useroptionsDescChaptersAsSections := useroptionsFields[5].Descriptor()
	// useroptions.DefaultChaptersAsSections holds the default value on creation for the chapters_as_sections field.
	useroptions.DefaultChaptersAsSections = useroptionsDescChaptersAsSections.Default.(bool)
	// useroptionsDescEmbedVideo is the schema descriptor for embed_video field.
	useroptionsDescEmbedVideo := useroptionsFields[6].Descriptor()
	// useroptions.DefaultEmbedVideo holds the default value on creation for the embed_video field.
	useroptions.DefaultEmbedVideo = useroptionsDescEmbedVideo.Default.(bool)
	// useroptionsDescIncludeDescription is the schema descriptor for include_description field.
	useroptionsDescIncludeDescription := useroptionsFields[7].Descriptor()
	// useroptions.DefaultIncludeDescription holds the default value on creation for the include_description field.
	useroptions.DefaultIncludeDescription = useroptionsDescIncludeDescription.Default.(bool)
	// useroptionsDescIncludeTags is the schema descriptor for include_tags field.
	useroptionsDescIncludeTags := useroptionsFields[8].Descriptor()
	// useroptions.DefaultIncludeTags holds the default value on creation for the include_tags field.
	useroptions.DefaultIncludeTags = useroptionsDescIncludeTags.Default.(bool)
}
